%MACRO SetLabelBlank(/*SET DATASET'S LABELs TO BLANK */
  DSN  /*DATASET NAME*/
  );
  %IF NOT %INDEX(&DSN,.) %THEN %LET DSN=WORK.&DSN;
  %PUT &DSN;
  %LOCAL LIB NAME;
  %LET LIB=%UPCASE(%SUBSTR(&DSN,1,%INDEX(&DSN,.)-1));
  %LET NAME=%UPCASE(%SUBSTR(&DSN,%INDEX(&DSN,.)+1));
  PROC SQL;
  SELECT " LABEL "||NAME||"= "" "";" INTO :LABELSTR SEPARATED BY " " 
  FROM  SASHELP.VCOLUMN
  WHERE LIBNAME="&LIB" AND
        MEMNAME="&NAME"
  ;
  DATA &DSN;
    SET &DSN;
    &LABELSTR;
  RUN; 
%MEND;
