/*/lillyce/non_study/users_sandbox/hui_liu/empty*/

%let indir1=/lillyce/non_study/users_sandbox/hui_liu/core;
%let indir2=F:\lillyce\prd\ly2940680\i4j_mc_hhbh\safety_review2\data\shared\sdtm;
%let indir3=/lillyce/prd/general/bums/macro_library;
%let indir4=/lillyce/qa/ly231514/h3e_cr_jmit/safety_review10/replica_programs/validator_component_modules;
%let indir5=/lillyce/non_study/users_sandbox/hui_liu/empty;
%let indir6=/lillyce/non_study/users_sandbox/hui_liu/empty;

%let outdir1=/lillyce/qa/ly231514/h3e_cr_jmit/safety_review10/replica_programs/replication_output;
%let outdir2=/lillyce/non_study/users_sandbox/hui_liu/temp;
%let outdir3=/lillyce/non_study/users_sandbox/hui_liu/temp;


%macro parse(dir);
%local x inorout;

%if %substr(&dir,1,2)=in %then %let inOrOut=in;
%else %let inOrOut=out;
%if &inorout=in %then %let x=%substr(&dir,6,1);
%else %let x=%substr(&dir,7,1);

%global &inorout.path&x &inorout.folder&x;
%let &inorout.path&x=%AHGup(&&&dir );
%let &inorout.folder&x=%AHGfilename(&&&dir );
/*%AHGpm(&inorout.path&x &inorout.folder&x );*/
%mend;
%parse(indir1);%parse(indir2);%parse(indir3);%parse(indir4);%parse(indir5);%parse(indir6);
%parse(outdir1);%parse(outdir2);%parse(outdir3);

OPTION nomprint nosource;
%PUT  ;
%PUT *****PACMAN****** DO NOT EDIT BELOW THIS LINE ******PACMAN***** ;
%PUT <?xml version="1.0" encoding="UTF-8"?> ;
%PUT <process sessionid="-5823c51f:1440dde4721:2a27" sddversion="3.5" cdvoption="N" parseroption="B"> ;
%PUT  <parameters> ;
%PUT   <parameter dependsaction="ENABLE" obfuscate="N" label="SAS log" systemtype="%nrstr(&star;LOG&star;)" tabname="System Files" baseoption="A" advanced="N" order="1" id="%nrstr(&star;LOG&star;)" canlinktobasepath="Y" protect="N" userdefined="S" filetype="LOG" ;
%PUT    processid="P3" required="N" resolution="INPUT" enable="N" type="LOGFILE"> ;
%PUT   </parameter> ;
%PUT   <parameter dependsaction="ENABLE" obfuscate="N" label="SAS output" systemtype="%nrstr(&star;LST&star;)" tabname="System Files" baseoption="A" advanced="N" order="2" id="%nrstr(&star;LST&star);" canlinktobasepath="Y" protect="N" userdefined="S" filetype="LST" ;
%PUT    processid="P3" required="N" resolution="INPUT" enable="N" type="LSTFILE"> ;
%PUT   </parameter> ;
%PUT   <parameter dependsaction="ENABLE" obfuscate="N" label="Process parameter values" systemtype="SDDPARMS" tabname="System Files" baseoption="A" advanced="N" order="3" id="SDDPARMS" canlinktobasepath="Y" protect="N" userdefined="S" filetype="SAS7BDAT" ;
%PUT    processid="P3" required="N" resolution="INPUT" enable="N" type="PARMFILE"> ;
%PUT   </parameter> ;
%PUT   <parameter dependsaction="ENABLE" obfuscate="N" label="SAS program" systemtype="%nrstr(&star;PGM&star;)" tabname="System Files" baseoption="A" advanced="N" order="4" id="%nrstr(&star;PGM&star;)" canlinktobasepath="Y" protect="N" userdefined="S" filetype="SAS" ;
%PUT    processid="P3" required="N" resolution="INPUT" enable="N" type="PGMFILE"> ;
%PUT   </parameter>;
%PUT   <parameter tabname="Parameters" id="INDIR1" expandfiletypes="N" obfuscate="N" label="Folder" required="N" order="5" baseoption="A" processid="P3" type="FOLDER" enable="N" canlinktobasepath="Y" readfiles="Y" protect="N" advanced="N" ;
%PUT    dependsaction="ENABLE" writefiles="N" resolution="INPUT"> ;
%PUT    <fileset setType="0"> ;
%PUT     <sourceContainer system="SDD" source="DOMAIN" displaypath="&inpath1" displayname="&infolder1" id="&indir1" itemtype="Container" fileinfoversion="3.0"> ;
%PUT     </sourceContainer> ;
%PUT     <filterList> ;
%PUT      <item name="ALL"> ;
%PUT      </item> ;
%PUT     </filterList> ;
%PUT    </fileset> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter tabname="Parameters" id="INDIR2" expandfiletypes="N" obfuscate="N" label="Folder" required="N" order="6" baseoption="A" processid="P3" type="FOLDER" enable="N" canlinktobasepath="Y" readfiles="Y" protect="N" advanced="N" ;
%PUT    dependsaction="ENABLE" writefiles="N" resolution="INPUT"> ;
%PUT    <fileset setType="0"> ;
%PUT     <sourceContainer system="SDD" source="DOMAIN" displaypath="&inpath2" displayname="&infolder2" id="&indir2" itemtype="Container" fileinfoversion="3.0"> ;
%PUT     </sourceContainer> ;
%PUT     <filterList> ;
%PUT      <item name="ALL"> ;
%PUT      </item> ;
%PUT     </filterList> ;
%PUT    </fileset> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter tabname="Parameters" id="INDIR3" expandfiletypes="N" obfuscate="N" label="Folder" required="N" order="7" baseoption="A" processid="P3" type="FOLDER" enable="N" canlinktobasepath="Y" readfiles="Y" protect="N" advanced="N" ;
%PUT    dependsaction="ENABLE" writefiles="N" resolution="INPUT"> ;
%PUT    <fileset setType="0"> ;
%PUT     <sourceContainer system="SDD" source="DOMAIN" displaypath="&inpath3" displayname="&infolder3" id="&indir3" itemtype="Container" fileinfoversion="3.0"> ;
%PUT     </sourceContainer> ;
%PUT     <filterList> ;
%PUT      <item name="ALL"> ;
%PUT      </item> ;
%PUT     </filterList> ;
%PUT    </fileset> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter obfuscate="N" writefiles="N" label="Folder" tabname="Parameters" baseoption="A" readfiles="Y" advanced="N" id="INDIR4" canlinktobasepath="Y" protect="N" expandfiletypes="N" required="N" resolution="INPUT" enable="N" type="FOLDER" ;
%PUT    order="8"> ;
%PUT    <fileset setType="0"> ;
%PUT     <sourceContainer system="SDD" source="DOMAIN" displaypath="&inpath4" displayname="&infolder4" id="&indir4" itemtype="Container" fileinfoversion="3.0"> ;
%PUT     </sourceContainer> ;
%PUT     <filterList> ;
%PUT      <item name="ALL"> ;
%PUT      </item> ;
%PUT     </filterList> ;
%PUT    </fileset> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter obfuscate="N" writefiles="N" label="Folder" tabname="Parameters" baseoption="A" readfiles="Y" advanced="N" id="INDIR5" canlinktobasepath="Y" protect="N" expandfiletypes="N" required="N" resolution="INPUT" enable="N" type="FOLDER" ;
%PUT    order="9"> ;
%PUT    <fileset setType="0"> ;
%PUT     <sourceContainer system="SDD" source="DOMAIN" displaypath="&inpath5" displayname="&infolder5" id="&indir5" itemtype="Container" fileinfoversion="3.0"> ;
%PUT     </sourceContainer> ;
%PUT     <filterList> ;
%PUT      <item name="ALL"> ;
%PUT      </item> ;
%PUT     </filterList> ;
%PUT    </fileset> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter obfuscate="N" id="OUTDIR1" canlinktobasepath="Y" expandfiletypes="N" protect="N" label="Folder" order="10" processid="P3" baseoption="A" resolution="INPUT" advanced="N" required="N" readfiles="N" enable="N" type="FOLDER" writefiles="Y" ;
%PUT    tabname="Parameters"> ;
%PUT    <file system="SDD" source="DOMAIN" displaypath="&OUTpath1" displayname="&outFolder1" id="&outdir1" itemtype="Container" fileinfoversion="3.0"> ;
%PUT    </file> ;
%PUT    <fileset setType="0"> ;
%PUT     <sourceContainer system="SDD" source="DOMAIN" displaypath="&outpath1" displayname="&outFolder1" id="&outdir1" itemtype="Container" fileinfoversion="3.0"> ;
%PUT     </sourceContainer> ;
%PUT     <filterList> ;
%PUT      <item name="ALL"> ;
%PUT      </item> ;
%PUT     </filterList> ;
%PUT    </fileset> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter obfuscate="N" writefiles="Y" label="Folder" tabname="Parameters" baseoption="A" readfiles="N" advanced="N" id="OUTDIR2" canlinktobasepath="Y" protect="N" expandfiletypes="N" required="N" resolution="INPUT" enable="N" type="FOLDER" ;
%PUT    order="11"> ;
%PUT    <file system="SDD" source="DOMAIN" displaypath="&OUTpath2" displayname="&outFolder2" id="&outdir2" itemtype="Container" fileinfoversion="3.0"> ;
%PUT    </file> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter obfuscate="N" writefiles="Y" label="Folder" tabname="Parameters" baseoption="A" readfiles="N" advanced="N" id="OUTDIR3" canlinktobasepath="Y" protect="N" expandfiletypes="N" required="N" resolution="INPUT" enable="N" type="FOLDER" ;
%PUT    order="12"> ;
%PUT    <file system="SDD" source="DOMAIN" displaypath="&OUTpath3" displayname="&outFolder3" id="&outdir3" itemtype="Container" fileinfoversion="3.0"> ;
%PUT    </file> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT   <parameter canlinktobasepath="N" dependsaction="ENABLE" id="LOCALTEMP" cdvenable="Y" cdvrequired="N" advanced="N" enable="N" obfuscate="N" maxlength="256" tabname="Parameters" resolution="INPUT" protect="N" label="Text field" required="N" ;
%PUT    type="TEXT" order="13"> ;
%PUT   </parameter> ;
%PUT   <parameter canlinktobasepath="N" dependsaction="ENABLE" id="CORE" cdvenable="Y" cdvrequired="N" advanced="N" enable="N" obfuscate="N" maxlength="256" tabname="Parameters" resolution="INPUT" protect="N" label="Text field" required="N" type="TEXT" ;
%PUT    order="14"> ;
%PUT   </parameter> ;
%PUT   <parameter canlinktobasepath="N" dependsaction="ENABLE" id="RAW" cdvenable="Y" cdvrequired="N" advanced="N" enable="N" obfuscate="N" maxlength="256" tabname="Parameters" resolution="INPUT" protect="N" label="Text field" required="N" type="TEXT" ;
%PUT    order="15"> ;
%PUT   </parameter> ;
%PUT   <parameter canlinktobasepath="N" dependsaction="ENABLE" id="THEOUT" cdvenable="Y" cdvrequired="N" advanced="N" enable="N" obfuscate="N" maxlength="256" tabname="Parameters" resolution="INPUT" protect="N" label="Text field" required="N" type="TEXT" ;
%PUT    order="16"> ;
%PUT   </parameter> ;
%PUT   <parameter canlinktobasepath="N" dependsaction="ENABLE" id="I" maximum="9999999" advanced="N" enable="N" obfuscate="N" tabname="Parameters" minimum="-9999999" numtype="real" resolution="INPUT" protect="N" label="Numeric field" required="N" ;
%PUT    type="NUMERIC" order="17"> ;
%PUT   </parameter> ;
%PUT   <parameter canlinktobasepath="N" dependsaction="ENABLE" id="ONE" cdvenable="Y" cdvrequired="N" advanced="N" enable="N" obfuscate="N" maxlength="256" tabname="Parameters" resolution="INPUT" protect="N" label="Text field" required="N" type="TEXT" ;
%PUT    order="18"> ;
%PUT   </parameter> ;
%PUT   <parameter canlinktobasepath="N" dependsaction="ENABLE" id="DSNS" cdvenable="Y" cdvrequired="N" advanced="N" enable="N" obfuscate="N" maxlength="256" tabname="Parameters" resolution="INPUT" protect="N" label="Text field" required="N" type="TEXT" ;
%PUT    order="19"> ;
%PUT   </parameter> ;
%PUT   <parameter tabname="Parameters" id="INDIR6" expandfiletypes="N" obfuscate="N" label="Folder" required="N" order="20" baseoption="A" processid="P3" type="FOLDER" enable="N" canlinktobasepath="Y" readfiles="Y" protect="N" advanced="N" ;
%PUT    dependsaction="ENABLE" writefiles="N" resolution="INPUT"> ;
%PUT    <fileset setType="0"> ;
%PUT     <sourceContainer system="SDD" source="DOMAIN" displaypath="&inpath6" displayname="&infolder6" id="&indir6" itemtype="Container" fileinfoversion="3.0"> ;
%PUT     </sourceContainer> ;
%PUT     <filterList> ;
%PUT      <item name="ALL"> ;
%PUT      </item> ;
%PUT     </filterList> ;
%PUT    </fileset> ;
%PUT    <description> ;
%PUT    </description> ;
%PUT   </parameter> ;
%PUT  </parameters> ;
%PUT </process> ;
%PUT  ;
%PUT *****PACMAN******************************************PACMAN*****;



