%macro attrv(ds=, var=, attrib=);

%******************************************************************************;
%*                          PAREXEL INTERNATIONAL LTD                          ;
%*                                                                             ;
%* CLIENT:            PAREXEL                                                  ;
%*                                                                             ;
%* PROJECT:           Dataset Attributes Macro                                 ;
%*                                                                             ;
%* TIMS CODE:         68372                                                    ;
%*                                                                             ;
%* SOPS FOLLOWED:     1213                                                     ;
%*                                                                             ;
%******************************************************************************;
%*                                                                             ;
%* PROGRAM NAME:      attrv.sas                                                ;
%*                                                                             ;
%* PROGRAM LOCATION:  /opt/pxlcommon/stats/macros/sas/code/attrv/ver002        ;
%*                                                                             ;
%******************************************************************************;
%*                                                                             ;
%* USER REQUIREMENTS: Macro to return an attribute of a dataset variable.      ;
%*                                                                             ;
%* TECHNICAL          The macro is programmed to return any attribute from any ;
%* SPECIFICATIONS:    dataset variable based on arguments passed as parameters ;
%*                    to macro.                                                ;
%*                    Macro provides error messages if attribute cannot be     ;
%*                    returned.                                                ;
%*                                                                             ;
%* INPUT:             Macro Parameters:                                        ;
%*                       DS     - Name of dataset containing variable.         ;
%*                       VAR    - Variable to return attribute for.            ;
%*                       ATTRIB - Attribute name.  The full list of variable   ;
%*                                attributes can be found in the SAS           ;
%*                                documentation.  The most common ones used    ;
%*                                will be VARTYPE, VARLEN, VARLABEL, VARFMT    ;
%*                                and VARINFMT.                                ;
%*                                                                             ;
%* OUTPUT:            N/A                                                      ;
%*                                                                             ;
%* PROGRAMS CALLED:   N/A                                                      ;
%*                                                                             ;
%* ASSUMPTIONS/       None                                                     ;
%* REFERENCES                                                                  ;
%*                                                                             ;
%*                                                                             ;
%******************************************************************************;
%*                                                                             ;
%* MODIFICATION HISTORY                                                        ;
%*-----------------------------------------------------------------------------;
%* VERSION:           1                                                        ;
%* AUTHOR:            Roland Rashleigh-Berry (External)                        ;
%* QC BY:             N/A                                                      ;
%*                                                                             ;
%*-----------------------------------------------------------------------------;
%* VERSION:           2                                                        ;
%*                                                                             ;
%* RISK ASSESSMENT                                                             ;
%* Business:          High   [ ]: System has direct impact on the provision of ;
%*                                business critical services either globally   ;
%*                                or at a regional level.                      ;
%*                    Medium [ ]: System has direct impact on the provision of ;
%*                                business critical services at a local level  ;
%*                                only.                                        ;
%*                    Low    [X]: System used to indirectly support the        ;
%*                                provision of a business critical service or  ;
%*                                operation at a global, regional or local     ;
%*                                level.                                       ;
%*                    None   [ ]: System has no impact on the provision of a   ;
%*                                business critical service or operation.      ;
%*                                                                             ;
%* Regulatory:        High   [ ]: System has a direct impact on GxP data and/  ;
%*                                or directly supports a GxP process.          ;
%*                    Medium [ ]: System has an indirect impact on GxP data    ;
%*                                and supports a GxP process.                  ;
%*                    Low    [X]: System has an indirect impact on GxP data or ;
%*                                supports a GxP process.                      ;
%*                    None   [ ]: System is not involved directly or           ;
%*                                indirectly with GxP data or a GxP process.   ;
%*                                                                             ;
%* REASON FOR CHANGE: 1) Validation of program to standards required by        ;
%*                       WSOP 1213.                                            ;
%*                    2) No changes to code required.                          ;
%*                                                                             ;
%* TESTING            Peer code review and review of test output created by    ;
%* METHODOLOGY:       Q:\Programming Steering Committee\SoftwareValidation\    ;
%*                    Software\SASMacros\Pageno\Attrv_Val.sas                  ;
%*                                                                             ;
%* DEVELOPER:         Roland Rashleigh-Berry (External) Date : 01/10/2002      ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%* CODE REVIEWER:     Dan Higgins                       Date : 07/03/2005      ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%* USER:              Dan Higgins                       Date : 07/03/2005      ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%******************************************************************************;
%* Tested on UNIX platform:-                                                   ;
%*                                                                             ;
%* USER:              Dan Higgins                       Date : 11/07/2005      ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%******************************************************************************;

%** DEFINE LOCAL MACRO VARIABLES ***;
%local dsid rc varnum;

%** ATTEMPT TO OPEN DATASET ***;
%let dsid=%sysfunc(open(&ds,is));

%** IF CANNOT OPEN DATASET PROVIDE MESSAGE TO LOG ***;
%if &dsid EQ 0 %then %do;
   %put ERROR: (attrv) Dataset &ds not opened due to the following reason:;
   %put %sysfunc(sysmsg());
%end;

%** ELSE IF DATASET OPENED ATTEMPT TO GET VARIABLE ATTRIBUTE ***;
%else %do;
   %let varnum=%sysfunc(varnum(&dsid,&var));
   %** IF VARIABLE DOES NOT EXIST ON DATASET PROVIDE MESSAGE TO LOG ***;
   %if &varnum lt 1 %then %put ERROR: (attrv) Variable &var not in dataset &ds;
   %** ELSE IF VARIABLE DOES EXIST GET VALUE OF ATTRIBUTE ***;
   %else %do;
      %sysfunc(&attrib(&dsid,&varnum))
   %end;
   %** CLOSE DATASET ***;
   %let rc=%sysfunc(close(&dsid));
%end;

%mend attrv;

