%macro chisq(indsn,print,var1,var2,by,byvars,where,weight,mergevar,outdsn);
%******************************************************************************;
%*                          PAREXEL INTERNATIONAL LTD                          ;
%*                                                                             ;
%* CLIENT:            PAREXEL                                                  ;
%*                                                                             ;
%* PROJECT:           Macro to caclulate Chi-squared p-value                   ;
%*                                                                             ;
%* TIMS CODE:         68372                                                    ;
%*                                                                             ;
%* SOPS FOLLOWED:     1213                                                     ;
%*                                                                             ;
%******************************************************************************;
%*                                                                             ;
%* PROGRAM NAME:      chisq.SAS                                                ;
%*                                                                             ;
%* PROGRAM LOCATION:  /opt/pxlcommon/stats/macros/sas/code/chisq/ver002        ;
%*                                                                             ;
%******************************************************************************;
%*                                                                             ;
%* USER REQUIREMENTS: Perform Chi-square test and create output dataset        ;
%*                     containing specified variables and p-value.  If (due to ;
%*                     lack of input data) no output dataset is created by     ;
%*                     PROC FREQ, the output dataset should still be created   ;
%*                     with p-value set to be missing                          ;
%*                                                                             ;
%* TECHNICAL          A PROC FREQ will be used to perform the Chi-squared test,;
%* SPECIFICATIONS:     and create an output dataset containing the Chi-squared ;
%*                     p-value. A check will be performed to see whether the   ;
%*                     output dataset exists, and if so the p-value will be    ;
%*                     formatted.  If the output dataset does not exist a      ;
%*                     blank p-value variable will be created.                 ;
%*                                                                             ;
%* INPUT:             Macro paramters:                                         ;
%*                      INDSN=input dataset name                               ;
%*                      PRINT=to add noprint option to suppress output         ;
%*                            (should take value NOPRINT or be missing)        ;
%*                      VAR1=input variable                                    ;
%*                      VAR2=input variable                                    ;
%*                      BY=by variable(s) (needs to include BY followed by a   ;
%*                         list of parameters)                                 ;
%*                      BYVARS=by variable(s) without by statement for keep    ;
%*                      WHERE=subsetting where clause (needs to include        ;
%*                            WHERE followed by where clause)                  ;
%*                      WEIGHT=weight variable                                 ;
%*                      MERGEVAR=merge variable                                ;
%*                      OUTDSN=output dataset name                             ;
%*                                                                             ;
%* OUTPUT:            An output dataset (name to be specified by &OUTDSN)      ;
%*                     conatining the &BYVARS variables and an additional      ;
%*                     variable (PVAL) conatining the Chi-squared p-value      ;
%*                                                                             ;
%* PROGRAMS CALLED:   N/A                                                      ;
%*                                                                             ;
%* ASSUMPTIONS/       None                                                     ;
%* REFERENCES:                                                                 ;
%*                                                                             ;
%******************************************************************************;
%*                                                                             ;
%* MODIFICATION HISTORY                                                        ;
%*-----------------------------------------------------------------------------;
%* VERSION:           1                                                        ;
%* AUTHOR:            Kerri McCaul (RTP)                                       ;
%* QC BY:             N/A                                                      ;
%*                                                                             ;
%*-----------------------------------------------------------------------------;
%* VERSION:           2                                                        ;
%*                                                                             ;
%* RISK ASSESSMENT                                                             ;
%* Business:          High   [ ]: System has direct impact on the provision of ;
%*                                business critical services either globally   ;
%*                                or at a regional level.                      ;
%*                    Medium [X]: System has direct impact on the provision of ;
%*                                business critical services at a local level  ;
%*                                only.                                        ;
%*                    Low    [ ]: System used to indirectly support the        ;
%*                                provision of a business critical service or  ;
%*                                operation at a global, regional or local     ;
%*                                level.                                       ;
%*                    None   [ ]: System has no impact on the provision of a   ;
%*                                business critical service or operation.      ;
%*                                                                             ;
%* Regulatory:        High   [X]: System has a direct impact on GxP data and/  ;
%*                                or directly supports a GxP process.          ;
%*                    Medium [ ]: System has an indirect impact on GxP data    ;
%*                                and supports a GxP process.                  ;
%*                    Low    [ ]: System has an indirect impact on GxP data or ;
%*                                supports a GxP process.                      ;
%*                    None   [ ]: System is not involved directly or           ;
%*                                indirectly with GxP data or a GxP process.   ;
%*                                                                             ;
%* REASON FOR CHANGE: 1) Validation of program to standards required by        ;
%*                       WSOP 1213.                                            ;
%*                    2) Changed name of initial output dataset in PROC FREQ   ;
%*                       to be the same as the final output dataset rather than;                                                          ;
%*                       STAT, as the macro would not work properly if a STAT  ;
%*                       dataset already existed, which is not too uncommon    ;
%*                                                                             ;
%* TESTING            Peer code review and review of the test output from      ;
%* METHODOLOGY:       CHISQ_VAL.SAS                                            ;
%*                                                                             ;
%* DEVELOPER:         Simon Gillis                      Date : 1 March 2005    ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%* CODE REVIEWER:     Phil Riley                        Date : 4 March 2005    ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%* USER:              Phil Riley                        Date : 4 March 2005    ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%******************************************************************************;
%* Tested on UNIX platform:-                                                   ;
%*                                                                             ;
%* USER:              Dan Higgins                       Date : 12/07/2005      ;
%*                                                                             ;
%* SIGNATURE:         ................................  Date : ............... ;
%*                                                                             ;
%******************************************************************************;


%local indsn print var1 var2 by byvars where weight mergevar outdsn;

proc freq data=&indsn &print;
  tables &var1*&var2 /chisq noprint;
  &by;
  &where;
  &weight;
  output out=&outdsn (keep=&byvars p_pchi) chisq;
run;

%if %sysfunc(exist(&OUTDSN)) %then %do;

  data &outdsn (drop=p_pchi);
    length pval $6.;
    set &outdsn;
    &mergevar;
    pval=put(round(p_pchi,.001),5.3);
  run;

%end;

%else %do;

  data &outdsn;
    length pval $6.;
    &mergevar;
    pval='';
  run;

%end;

%mend chisq;



