%MACRO Univar(indsn,var,by,where,outdsn);

   %******************************************************************************;
   %*                          PAREXEL INTERNATIONAL LTD                          ;
   %*                                                                             ;
   %* CLIENT:            PAREXEL                                                  ;
   %*                                                                             ;
   %* PROJECT:           Univar.sas [Macro for producing a PROC UNIVARIATE        ;
   %*                                output]                                      ;
   %*                                                                             ;
   %* TIMS CODE:         68372                                                    ;
   %*                                                                             ;
   %* SOPS FOLLOWED:     1213                                                     ;
   %*                                                                             ;
   %******************************************************************************;
   %*                                                                             ;
   %* PROGRAM NAME:      Univar.SAS                                               ;
   %*                                                                             ;
   %* PROGRAM LOCATION:  /opt/pxlcommon/stats/macros/sas/code/univar/ver002       ;
   %*                                                                             ;
   %******************************************************************************;
   %*                                                                             ;
   %* USER REQUIREMENTS: Perform Proc Univariate and create output dataset        ;
   %*                    containing specified variables.                          ;
   %*                                                                             ;
   %* TECHNICAL          The input variables will be used in a Proq Univariate to ;
   %* SPECIFICATIONS:    produce the output dataset.                              ;
   %*                                                                             ;
   %* INPUT:             Macro paramters:                                         ;
   %*                                                                             ;
   %*                    INDSN  = input dataset name                              ;
   %*                             (should take value NOPRINT or be missing)       ;
   %*                    VAR    = input variable                                  ;
   %*                    BY     = by variable(s) (needs to include BY followed by ;
   %*                             a list of parameters)                           ;
   %*                    WHERE  = subsetting where clause (needs to include       ;
   %*                             WHERE followed by where clause)                 ;
   %*                    OUTDSN = output dataset name                             ;
   %*                                                                             ;
   %* OUTPUT:            An output dataset (name to be specified by &OUTDSN)      ;
   %*                    containing the &BYVARS variables and univariate          ;
   %*                    parameters                                               ;
   %*                                                                             ;
   %* PROGRAMS CALLED:   N/A                                                      ;
   %*                                                                             ;
   %* ASSUMPTIONS/       None                                                     ;
   %* REFERENCES:                                                                 ;
   %*                                                                             ;
   %******************************************************************************;
   %*                                                                             ;
   %* MODIFICATION HISTORY                                                        ;
   %*-----------------------------------------------------------------------------;
   %* VERSION:           1                                                        ;
   %* AUTHOR:            Kerri McCaul (RTP) 05/02/2003                            ;
   %* QC BY:             N/A                                                      ;
   %*                                                                             ;
   %*-----------------------------------------------------------------------------;
   %* VERSION:           2                                                        ;
   %*                                                                             ;
   %* RISK ASSESSMENT                                                             ;
   %* Business:          High   [X]: System has direct impact on the provision of ;
   %*                                business critical services either globally   ;
   %*                                or at a regional level.                      ;
   %*                    Medium [ ]: System has direct impact on the provision of ;
   %*                                business critical services at a local level  ;
   %*                                only.                                        ;
   %*                    Low    [ ]: System used to indirectly support the        ;
   %*                                provision of a business critical service or  ;
   %*                                operation at a global, regional or local     ;
   %*                                level.                                       ;
   %*                    None   [ ]: System has no impact on the provision of a   ;
   %*                                business critical service or operation.      ;
   %*                                                                             ;
   %* Regulatory:        High   [X]: System has a direct impact on GxP data and/  ;
   %*                                or directly supports a GxP process.          ;
   %*                    Medium [ ]: System has an indirect impact on GxP data    ;
   %*                                and supports a GxP process.                  ;
   %*                    Low    [ ]: System has an indirect impact on GxP data or ;
   %*                                supports a GxP process.                      ;
   %*                    None   [ ]: System is not involved directly or           ;
   %*                                indirectly with GxP data or a GxP process.   ;
   %*                                                                             ;
   %* REASON FOR CHANGE: 1) Validation of program to standards required by        ;
   %*                       WSOP 1213.                                            ;
   %*                    2) No changes to code required.                          ;
   %*                                                                             ;
   %* TESTING            Peer code review and review of the test output from      ;
   %* METHODOLOGY:       Q:\Programming Steering Committee\SoftwareValidation\    ;
   %*                    Software\SASMacros\Univar\Univar_val.sas                 ;
   %*                                                                             ;
   %* DEVELOPER:         Kerri McCaul                      Date : 1 March 2005    ;
   %*                                                                             ;
   %* SIGNATURE:         ................................  Date : ............... ;
   %*                                                                             ;
   %* CODE REVIEWER:     Phil Riley                        Date : 3 March 2005    ;
   %*                                                                             ;
   %* SIGNATURE:         ................................  Date : ............... ;
   %*                                                                             ;
   %* USER:              Phil Riley                        Date : 3 March 2005    ;
   %*                                                                             ;
   %* SIGNATURE:         ................................  Date : ............... ;
   %*                                                                             ;
   %******************************************************************************;
   %* Tested on UNIX platform:-                                                   ;
   %*                                                                             ;
   %* USER:              Dan Higgins                       Date : 18/07/2005      ;
   %*                                                                             ;
   %* SIGNATURE:         ................................  Date : ............... ;
   %*                                                                             ;
   %******************************************************************************;

   %local indsn var by where outdsn;

   proc univariate data=&indsn noprint;
      var &var;
      &by;
      &where;
      output out=&outdsn n=n mean=mean std=std median=median q1=q1 q3=q3
             nmiss=nmiss min=min max=max stdmean=stdmean;
   run;

%MEND Univar;
