#!/bin/sh
#******************************************************************************
#Sponsor name: PXL
#Study name: NA
#PAREXEL number: NA
#
#Program name: chk_comp 
#Program location: /home/users/<userid>/shellscripts/
#
#Requirements/Purpose: To scan SAS compare result *.txt for Unequal is not zero, Sequence Number for .* as, Variable Order
# 					   not in, Differing Attributes, not EXACTLY Equal and Conflicting Types
#References: This is an QC tool to ensure compare result have normal output.
#
#Assumptions: entry the qc_*.txt to scan
#
#Input:  qc_*.txt
#
#Output: NA
#
#Programs called: NA
#
#******************************************************************************
#
#Version: 1
#
#Release Date: 19Sep2014
#
#Developer/Programmer: Hsi-Min Yang
#******************************************************************************
#******************************************************************************
#
#Release Date: 03Dec2015
#
#Developer/Programmer: Allen Zeng
#
#Detail of Change: Update the regular expression and add three terms:
#                  1. Both datasets have 0 obs
#		     2. Main or QC dataset is from the work library
#                  3. The program was run in interactive mode
#******************************************************************************

if [ $# -lt 1 ]
then
    for file in qc_*.txt
    do 
      	cat $file|egrep "Total Number of Values which Compare Unequal: [^0]|Number of (Variables|Observations) in .* but not in|Number of Variables with Differing Attributes:|Total Number of Values not EXACTLY Equal:|Conflicting Types|Variable Order|Sequence Number for .* as"|awk -v file="$file" 'BEGIN{FS=OFS=","; print file " ====>"} {gsub(/^[ \t]+|[ \t]+$/, "", $0)} {print "\t \t" FNR ": " $0}'
  	cat $file|egrep '[ ]*[A-Z_]+\.?[A-Z]*[ ]+[0-9]{2}[A-Z]{3}.*[]+[0-9]{2}[A-Z]{3}.*[0-9]+[]+[0-9]+[ ]+.*$'|sed -e 's/.*[0-9]\{1,\}[ ]\{1,\}\(.*\)/ \1/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {if ($1!= $2) {print "\t \t!!Datasets difference labels: Main =" $1 "          Qc ="  $2 } else if ($1==" " && $2 ==" ") {print "\t \t!!Both datasets have no label.!!"} }' 
  	cat $file|egrep '[ ]*[A-Z_]+\.?[A-Z]*[ ]+[0-9]{2}[A-Z]{3}.*[]+[0-9]{2}[A-Z]{3}.*[0-9]+[]+[0-9]+[ ]+.*$'|sed -e 's/.*[ ]\{1,\}\([0-9]\{1,\}\)[ ]\{1,\}.*/\1/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {if ($1=="0" && $2 =="0") {print "\t \t!!Both datasets have 0 obs.!!"} }' 
  	cat $file|egrep '[ ]*[A-Z_]+\.?[A-Z]*[ ]+[0-9]{2}[A-Z]{3}.*[]+[0-9]{2}[A-Z]{3}.*[0-9]+[]+[0-9]+[ ]+.*$'|sed -e 's/[ ]*\([A-Z]*\)\..*/\1/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {if ($1 =="WORK") {print "\t \t!!Main or QC dataset is from the work library.!!"} }' 
       cat $file|egrep 'X{25,}'|sed -e 's/.*/The program was run in interactive mode/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {print "\t \t!!The program was run in interactive mode.!!"}' 
    done
else
    while [ $# -ge 1 ]
    do
      	cat $1|egrep "Total Number of Values which Compare Unequal: [^0]|Number of (Variables|Observations) in .* but not in|Number of Variables with Differing Attributes:|Total Number of Values not EXACTLY Equal:|Conflicting Types|Variable Order|Sequence Number for .* as"|awk -v file="$1" 'BEGIN{FS=OFS=","; print file " ====>"} {gsub(/^[ \t]+|[ \t]+$/, "", $0)} {print "\t \t" FNR ": " $0}'
  	cat $1|egrep '[ ]*[A-Z_]+\.?[A-Z]*[ ]+[0-9]{2}[A-Z]{3}.*[]+[0-9]{2}[A-Z]{3}.*[0-9]+[]+[0-9]+[ ]+.*$'|sed -e 's/.*[0-9]\{1,\}[ ]\{1,\}\(.*\)/ \1/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {if ($1!= $2) {print "\t \t!!Datasets difference labels: Main =" $1 "          Qc ="  $2 } else if ($1==" " && $2 ==" ") {print "\t \t!!Both datasets have no label.!!"} }' 
  	cat $1|egrep '[ ]*[A-Z_]+\.?[A-Z]*[ ]+[0-9]{2}[A-Z]{3}.*[]+[0-9]{2}[A-Z]{3}.*[0-9]+[]+[0-9]+[ ]+.*$'|sed -e 's/.*[ ]\{1,\}\([0-9]\{1,\}\)[ ]\{1,\}.*/\1/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {if ($1=="0" && $2 =="0") {print "\t \t!!Both datasets have 0 obs.!!"} }' 
  	cat $1|egrep '[ ]*[A-Z_]+\.?[A-Z]*[ ]+[0-9]{2}[A-Z]{3}.*[]+[0-9]{2}[A-Z]{3}.*[0-9]+[]+[0-9]+[ ]+.*$'|sed -e 's/[ ]*\([A-Z]*\)\..*/\1/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {if ($1 =="WORK") {print "\t \t!!Main or QC dataset is from the work library.!!"} }' 
	cat $1|egrep 'X{25,}'|sed -e 's/.*/The program was run in interactive mode/'|awk 'BEGIN{FS="\n";RS="";OFS=" " } {print "\t \t!!The program was run in interactive mode.!!"}' 
	 shift
    done
fi